tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "luckyframework/lucky"
tap "mapbox/cli"
tap "pothosware/pothos"
tap "rcmdnk/file"
brew "autoconf"
brew "automake"
brew "composer"
brew "curl"
brew "docker", link: false
brew "gettext"
brew "gist"
brew "git"
brew "git-flow"
brew "libtool"
brew "imagemagick"
brew "ipfs"
brew "isl"
brew "memcached"
brew "libmemcached"
brew "libssh2"
brew "libxml2"
brew "libyaml"
brew "lynx"
brew "mariadb", restart_service: true
brew "mas"
brew "mhash"
brew "mcrypt"
brew "mongodb", restart_service: true
brew "nginx", restart_service: true
brew "nvm"
brew "openssl@1.1"
brew "php", restart_service: true
brew "php-cs-fixer"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "python"
brew "redis", restart_service: true
brew "watchman"
brew "wget"
brew "yarn"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "android-studio"
cask "bartender"
cask "chromium"
cask "daisydisk"
cask "dash"
cask "docker"
cask "docker-toolbox"
cask "dropbox"
cask "expo-xde"
cask "firefox"
cask "flux"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-drive-file-stream"
cask "graphiql"
cask "istat-menus"
cask "java"
cask "jaxx"
cask "kitematic"
cask "macdown"
cask "microsoft-office"
cask "monolingual"
cask "ngrok"
cask "omniplan"
cask "openoffice"
cask "paragon-ntfs"
cask "postman"
cask "sketch"
cask "sketch-toolbox"
cask "sketchpacks"
cask "spotify"
cask "tableplus"
cask "teamviewer"
cask "ticktick"
cask "transmit"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/fonts/font-menlo-for-powerline"
mas "Day One", id: 1055511498
mas "GIPHY CAPTURE", id: 668208984
mas "Icon Set Creator", id: 939343785
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Typeface", id: 1062679359
mas "typeface", id: 1062679359
mas "Xcode", id: 497799835
