tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/fuse"
tap "homebrew/science"
tap "homebrew/services"
tap "luckyframework/lucky"
tap "mapbox/cli"
tap "pothosware/pothos"
tap "rcmdnk/file"
brew "autoconf"
brew "automake"
brew "isl"
brew "curl"
brew "docker", link: false
brew "gettext"
brew "gist"
brew "git"
brew "git-flow"
brew "libtool"
brew "imagemagick"
brew "ipfs"
brew "memcached"
brew "libmemcached"
brew "libxml2"
brew "mas"
brew "postgresql", restart_service: true
brew "python"
brew "redis", restart_service: true
brew "wget"
brew "yarn"
cask "android-studio"
cask "bartender"
cask "chromium"
cask "daisydisk"
cask "docker"
cask "docker-toolbox"
cask "dropbox"
cask "firefox"
cask "github"
cask "google-chrome"
cask "google-drive-file-stream"
cask "graphiql"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "jaxx"
cask "kitematic"
cask "macdown"
cask "microsoft-office"
cask "monolingual"
cask "ngrok"
cask "omniplan"
cask "openoffice"
cask "paragon-ntfs"
cask "postman"
cask "sketch"
cask "sketch-toolbox"
cask "sketchpacks"
cask "spotify"
cask "tableplus"
cask "teamviewer"
cask "ticktick"
cask "transmit"
cask "unrarx"
cask "utorrent"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "expo-xde"
cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/fonts/font-menlo-for-powerline"
mas "Dayone", id: 1055511498
mas "GIPHY", id: 668208984
mas "Icon Set Creator", id: 939343785
mas "Keka", id: 470158793
mas "Keynote", id: 409183694
mas "Line", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Typeface", id: 1062679359
mas "Xcode", id: 497799835
